#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$script_dir/../pony/scripts/pony-paths.sh"

source_pony_root="$pony_root"
source_pony_bin_dir="$pony_bin_dir"
source_pony_scripts_dir="$pony_scripts_dir"
source_pony_launch_prompts_dir="$pony_launch_prompts_dir"

target_root="${1:-$PWD}"
load_project_paths "$target_root"

while IFS= read -r dir; do
  mkdir -p "$dir"
done < <(project_pony_dirs)

write_file_if_missing() {
  local path="${1:?missing path}"
  local content="${2-}"
  if [[ ! -e "$path" ]]; then
    printf '%s' "$content" >"$path"
  fi
}

copy_file_if_missing() {
  local source_path="${1:?missing source path}"
  local target_path="${2:?missing target path}"
  if [[ ! -e "$target_path" ]]; then
    cp "$source_path" "$target_path"
  fi
}

write_managed_executable() {
  local path="${1:?missing path}"
  local content="${2-}"
  printf '%s' "$content" >"$path"
  chmod +x "$path"
}

write_managed_file() {
  local path="${1:?missing path}"
  local content="${2-}"
  printf '%s' "$content" >"$path"
}

write_workfile_if_missing() {
  local slug="${1:?missing worker slug}"
  local title
  title="$(worker_label_for_slug "$slug")"
  local workfile="$AGENIC_PROJECT_PONY_WORK_DIR/$(workfile_name_for_slug "$slug")"
  write_file_if_missing "$workfile" "$(cat <<EOF
# ${title} Workfile

Project: $AGENIC_PROJECT_NAME
Branch: $AGENIC_PROJECT_BRANCH

Status: blank
Scope: unassigned
Notes:
- no assigned work yet
EOF
)"
}

write_project_config_if_missing() {
  write_file_if_missing "$AGENIC_PROJECT_PONY_CONFIG_PATH" "$(cat <<EOF
project_name: $AGENIC_PROJECT_NAME
project_root: $AGENIC_PROJECT_ROOT
branch: $AGENIC_PROJECT_BRANCH
launcher_prefix: $AGENIC_PROJECT_NAME Pony
agenic_system_root: $agenic_root
EOF
)"
}

is_agenic_source_project() {
  [[ "$AGENIC_PROJECT_ROOT" == "$agenic_root" ]]
}

write_shell_launcher_if_missing() {
  local path="${1:?missing launcher path}"
  local personality="${2:?missing personality}"
  write_managed_executable "$path" "$(cat <<EOF
#!/usr/bin/env bash
set -euo pipefail
cd "$AGENIC_PROJECT_ROOT"
exec "$AGENIC_PROJECT_PONY_SCRIPTS_DIR/launch-in-pony-shell.sh" "$personality"
EOF
)"
}

remove_if_exists() {
  local path="${1:?missing path}"
  rm -f "$path"
}

write_status_if_missing() {
  local slug="${1:?missing worker slug}"
  local branch_verified="yes"
  if [[ "$AGENIC_PROJECT_BRANCH" == "no-git-branch" ]]; then
    branch_verified="n/a"
  fi
  write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/${slug}.status.md" "$(cat <<EOF
AUDIENCE: EVERYONE
BRANCH: $AGENIC_PROJECT_BRANCH
WORKTREE: $AGENIC_PROJECT_ROOT
BRANCH_VERIFIED: $branch_verified
STATUS: WAITING
PUSH_STATUS: clean_local_branch
FILES_PLANNED: none
FILES_TOUCHED: none
BLOCKERS: none
NEXT_STEP: waiting for a concrete task
QUESTIONS_FOR_TWI: none
DECISION_NEEDED: none
EOF
)"
}

write_mailbox_if_missing() {
  local slug="${1:?missing worker slug}"
  local upper_name
  upper_name="$(printf '%s' "$slug" | tr '[:lower:]' '[:upper:]')"
  write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/${slug}.mailbox.md" "$(cat <<EOF
# ${upper_name} MAILBOX

## Pending Items
- none

EOF
)"
}

write_file_if_missing "$AGENIC_PROJECT_PONY_DIR/README.md" "$(cat <<EOF
# pony

Project-local pony runtime state for $AGENIC_PROJECT_NAME.

This directory is generated by:
$agenic_root/scripts/bootstrap-project.sh
EOF
)"

write_file_if_missing "$AGENIC_PROJECT_PONY_RUNTIME_STATE_PATH" "$(cat <<EOF
idle
EOF
)"

write_file_if_missing "$AGENIC_PROJECT_PONY_RUNTIME_PENDING_NOTICE_PATH" ""
write_file_if_missing "$AGENIC_PROJECT_PONY_RUNTIME_PENDING_NOTICE_SEEN_PATH" ""
write_file_if_missing "$AGENIC_PROJECT_PONY_RUNTIME_ACTIVE_PROMPT_PATH" ""
write_file_if_missing "$AGENIC_PROJECT_PONY_RUNTIME_DRAFT_PATH" ""

write_project_config_if_missing

for prompt_template in "$source_pony_launch_prompts_dir"/*.txt; do
  write_managed_file "$AGENIC_PROJECT_PONY_LAUNCH_PROMPTS_DIR/$(basename "$prompt_template")" "$(cat "$prompt_template")"
done

if [[ -d "$source_pony_root/assets" ]] && [[ "$source_pony_root/assets" != "$AGENIC_PROJECT_PONY_ASSETS_DIR" ]]; then
  cp -R "$source_pony_root/assets/." "$AGENIC_PROJECT_PONY_ASSETS_DIR/"
fi

if ! is_agenic_source_project && [[ -d "$agenic_root/vendor/prompt_toolkit" ]]; then
  command rm -rf "$AGENIC_PROJECT_PONY_VENDOR_DIR/prompt_toolkit"
  cp -R "$agenic_root/vendor/prompt_toolkit" "$AGENIC_PROJECT_PONY_VENDOR_DIR/"
fi

for managed_bin in codex-prompt-style.sh ponyalert ponydone codex-restart; do
  if [[ -f "$source_pony_bin_dir/$managed_bin" ]]; then
    write_managed_executable "$AGENIC_PROJECT_PONY_BIN_DIR/$managed_bin" "$(cat "$source_pony_bin_dir/$managed_bin")"
  fi
done

for managed_script in \
  codex-tmux-monitor.sh \
  pony-paths.sh \
  enter-twi-session.sh \
  enter-worker-and-codex.sh \
  enter-worker-from-prompt-file.sh \
  enter-worker-shell.sh \
  launch-worker.sh \
  pony-line-editor.py \
  pony-session-host.py \
  start-session.sh \
  warm-codex-tui.sh \
  watch-twi.sh \
  worker-postflight.sh \
  worker-preflight.sh
do
  if [[ -f "$source_pony_scripts_dir/$managed_script" ]]; then
    write_managed_executable "$AGENIC_PROJECT_PONY_SCRIPTS_DIR/$managed_script" "$(cat "$source_pony_scripts_dir/$managed_script")"
  fi
done

write_managed_file "$AGENIC_PROJECT_PONY_SCRIPTS_DIR/pony.zsh.support.zsh" "$(cat "$source_pony_scripts_dir/pony.zsh.support.zsh")"
write_managed_executable "$AGENIC_PROJECT_PONY_SCRIPTS_DIR/launch-in-pony-shell.sh" "$(cat "$source_pony_scripts_dir/launch-in-pony-shell.sh")"
write_managed_executable "$AGENIC_PROJECT_PONY_SCRIPTS_DIR/queue-runtime.sh" "$(cat "$source_pony_scripts_dir/queue-runtime.sh")"

if ! is_agenic_source_project; then
  write_managed_executable "$AGENIC_PROJECT_PONY_BIN_DIR/codex-pony" "$(cat <<EOF
#!/usr/bin/env bash
set -euo pipefail
exec "$agenic_root/pony/bin/codex-pony" "\$@"
EOF
)"

  write_managed_executable "$AGENIC_PROJECT_PONY_SCRIPTS_DIR/start-session.sh" "$(cat <<EOF
#!/usr/bin/env bash
set -euo pipefail
exec "$agenic_root/pony/scripts/start-session.sh" "\${1:?missing personality}" "$AGENIC_PROJECT_ROOT"
EOF
)"
fi

write_shell_launcher_if_missing "$AGENIC_PROJECT_PONY_BIN_DIR/pony-team-twi" "TWILIGHT_SPARKLE"
if ! is_agenic_source_project; then
  write_shell_launcher_if_missing "$AGENIC_PROJECT_PONY_BIN_DIR/pony-aj" "APPLEJACK"
  write_managed_executable "$AGENIC_PROJECT_PONY_BIN_DIR/pony-team" "$(cat <<EOF
#!/usr/bin/env bash
set -euo pipefail
cd "$AGENIC_PROJECT_ROOT"
printf '%s\n' "Project-local launcher set:"
printf '%s\n' "- ./pony/bin/pony-team-twi"
if [[ -x ./pony/bin/pony-aj ]]; then
  printf '%s\n' "- ./pony/bin/pony-aj"
fi
printf '%s\n' ""
printf '%s\n' "Warp users can use the generated project-specific launch configurations under:"
printf '%s\n' "./pony/launch.configs"
EOF
)"
else
  remove_if_exists "$AGENIC_PROJECT_PONY_BIN_DIR/pony-aj"
  remove_if_exists "$AGENIC_PROJECT_PONY_BIN_DIR/pony-team"
fi

write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/assignment.registry.tsv" "$(cat <<EOF
assignment_id	worker_label	personality	repo	branch	worktree	workfile	promptfile	scope
aj	AJ	APPLEJACK	$AGENIC_PROJECT_NAME	$AGENIC_PROJECT_BRANCH	$AGENIC_PROJECT_ROOT	$AGENIC_PROJECT_PONY_WORK_DIR/aj.md	$AGENIC_PROJECT_PONY_LAUNCH_PROMPTS_DIR/aj.txt	unassigned
pinkie	Pinkie	PINKIE_PIE	$AGENIC_PROJECT_NAME	$AGENIC_PROJECT_BRANCH	$AGENIC_PROJECT_ROOT	$AGENIC_PROJECT_PONY_WORK_DIR/pinkie.md	$AGENIC_PROJECT_PONY_LAUNCH_PROMPTS_DIR/pinkie.txt	unassigned
fs	FS	FLUTTERSHY	$AGENIC_PROJECT_NAME	$AGENIC_PROJECT_BRANCH	$AGENIC_PROJECT_ROOT	$AGENIC_PROJECT_PONY_WORK_DIR/fs.md	$AGENIC_PROJECT_PONY_LAUNCH_PROMPTS_DIR/fs.txt	unassigned
rarity	Rarity	RARITY	$AGENIC_PROJECT_NAME	$AGENIC_PROJECT_BRANCH	$AGENIC_PROJECT_ROOT	$AGENIC_PROJECT_PONY_WORK_DIR/rarity.md	$AGENIC_PROJECT_PONY_LAUNCH_PROMPTS_DIR/rarity.txt	unassigned
rd	RD	RAINBOW_DASH	$AGENIC_PROJECT_NAME	$AGENIC_PROJECT_BRANCH	$AGENIC_PROJECT_ROOT	$AGENIC_PROJECT_PONY_WORK_DIR/rd.md	$AGENIC_PROJECT_PONY_LAUNCH_PROMPTS_DIR/rd.txt	unassigned
spike	Spike	SPIKE	$AGENIC_PROJECT_NAME	$AGENIC_PROJECT_BRANCH	$AGENIC_PROJECT_ROOT	$AGENIC_PROJECT_PONY_WORK_DIR/spike.md	$AGENIC_PROJECT_PONY_LAUNCH_PROMPTS_DIR/spike.txt	unassigned
twi	Twilight	TWILIGHT_SPARKLE	$AGENIC_PROJECT_NAME	$AGENIC_PROJECT_BRANCH	$AGENIC_PROJECT_ROOT	$AGENIC_PROJECT_PONY_WORK_DIR/coordinator-twi.md	$AGENIC_PROJECT_PONY_LAUNCH_PROMPTS_DIR/twi.txt	coordinate the team
EOF
)"

for slug in aj pinkie fs rarity rd spike twi; do
  write_workfile_if_missing "$slug"
  write_status_if_missing "$slug"
  write_mailbox_if_missing "$slug"
done

write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/twi.todo.md" "$(cat <<EOF
# TWILIGHT TODO

Generated: blank

No pending Twilight questions or decisions.
EOF
)"

write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/twi.decisions.md" "$(cat <<EOF
# TWILIGHT DECISIONS

## Active Decisions
- none
EOF
)"

write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/twi.event.stream.history.md" "$(cat <<EOF
# TWILIGHT EVENT STREAM HISTORY

## Current State
- pending_review_needed_content: none
EOF
)"

write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/multi.agent.control.md" "$(cat <<EOF
# MULTI AGENT CONTROL

Blank project-local coordination state for $AGENIC_PROJECT_NAME on $AGENIC_PROJECT_BRANCH.
EOF
)"

write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/twi.review-needed" ""

write_file_if_missing "$AGENIC_PROJECT_PONY_LINUX_SHELL_MARKER" ""

cat <<EOF
Bootstrapped project-local pony state.
- project_root: $AGENIC_PROJECT_ROOT
- branch: $AGENIC_PROJECT_BRANCH
- pony_root: $AGENIC_PROJECT_PONY_DIR
- shell_launchers: $AGENIC_PROJECT_PONY_BIN_DIR/pony-team-twi$(if ! is_agenic_source_project; then printf ', %s, %s' "$AGENIC_PROJECT_PONY_BIN_DIR/pony-team" "$AGENIC_PROJECT_PONY_BIN_DIR/pony-aj"; fi)
EOF
