#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$script_dir/../pony/scripts/pony-paths.sh"

target_root="${1:-$PWD}"
load_project_paths "$target_root"

mkdir -p "$AGENIC_STATE_ROOT" "$AGENIC_AGENT_WORK_DIR" "$AGENIC_TEAM_COORDINATION_DIR"

write_file_if_missing() {
  local path="${1:?missing path}"
  local content="${2-}"
  if [[ ! -e "$path" ]]; then
    printf '%s' "$content" >"$path"
  fi
}

write_workfile_if_missing() {
  local slug="${1:?missing worker slug}"
  local title
  title="$(worker_label_for_slug "$slug")"
  local workfile="$AGENIC_AGENT_WORK_DIR/$(workfile_name_for_slug "$slug")"
  write_file_if_missing "$workfile" "$(cat <<EOF
# ${title} Workfile

Project: $AGENIC_PROJECT_NAME
Branch: $AGENIC_PROJECT_BRANCH

Status: blank
Scope: unassigned
Notes:
- no assigned work yet
EOF
)"
}

write_status_if_missing() {
  local slug="${1:?missing worker slug}"
  local branch_verified="yes"
  if [[ "$AGENIC_PROJECT_BRANCH" == "no-git-branch" ]]; then
    branch_verified="n/a"
  fi
  write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/${slug}.status.md" "$(cat <<EOF
AUDIENCE: EVERYONE
BRANCH: $AGENIC_PROJECT_BRANCH
WORKTREE: $AGENIC_PROJECT_ROOT
BRANCH_VERIFIED: $branch_verified
STATUS: WAITING
PUSH_STATUS: clean_local_branch
FILES_PLANNED: none
FILES_TOUCHED: none
BLOCKERS: none
NEXT_STEP: waiting for a concrete task
QUESTIONS_FOR_TWI: none
DECISION_NEEDED: none
EOF
)"
}

write_mailbox_if_missing() {
  local slug="${1:?missing worker slug}"
  local upper_name
  upper_name="$(printf '%s' "$slug" | tr '[:lower:]' '[:upper:]')"
  write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/${slug}.mailbox.md" "$(cat <<EOF
# ${upper_name} MAILBOX

## Pending Items
- none

EOF
)"
}

write_file_if_missing "$AGENIC_STATE_ROOT/README.md" "$(cat <<EOF
# .agenic-pony

Project-local Agenic Pony state for $AGENIC_PROJECT_NAME.

This directory is generated by:
$agenic_root/scripts/bootstrap-project.sh
EOF
)"

write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/assignment.registry.tsv" "$(cat <<EOF
assignment_id	worker_label	personality	repo	branch	worktree	workfile	promptfile	scope
aj	AJ	APPLEJACK	$AGENIC_PROJECT_NAME	$AGENIC_PROJECT_BRANCH	$AGENIC_PROJECT_ROOT	$AGENIC_AGENT_WORK_DIR/aj.md	$pony_launch_prompts_dir/aj.txt	unassigned
pinkie	Pinkie	PINKIE_PIE	$AGENIC_PROJECT_NAME	$AGENIC_PROJECT_BRANCH	$AGENIC_PROJECT_ROOT	$AGENIC_AGENT_WORK_DIR/pinkie.md	$pony_launch_prompts_dir/pinkie.txt	unassigned
fs	FS	FLUTTERSHY	$AGENIC_PROJECT_NAME	$AGENIC_PROJECT_BRANCH	$AGENIC_PROJECT_ROOT	$AGENIC_AGENT_WORK_DIR/fs.md	$pony_launch_prompts_dir/fs.txt	unassigned
rarity	Rarity	RARITY	$AGENIC_PROJECT_NAME	$AGENIC_PROJECT_BRANCH	$AGENIC_PROJECT_ROOT	$AGENIC_AGENT_WORK_DIR/rarity.md	$pony_launch_prompts_dir/rarity.txt	unassigned
rd	RD	RAINBOW_DASH	$AGENIC_PROJECT_NAME	$AGENIC_PROJECT_BRANCH	$AGENIC_PROJECT_ROOT	$AGENIC_AGENT_WORK_DIR/rd.md	$pony_launch_prompts_dir/rd.txt	unassigned
spike	Spike	SPIKE	$AGENIC_PROJECT_NAME	$AGENIC_PROJECT_BRANCH	$AGENIC_PROJECT_ROOT	$AGENIC_AGENT_WORK_DIR/spike.md	$pony_launch_prompts_dir/spike.txt	unassigned
twi	Twilight	TWILIGHT_SPARKLE	$AGENIC_PROJECT_NAME	$AGENIC_PROJECT_BRANCH	$AGENIC_PROJECT_ROOT	$AGENIC_AGENT_WORK_DIR/coordinator-twi.md	$pony_launch_prompts_dir/twi.txt	coordinate the team
EOF
)"

for slug in aj pinkie fs rarity rd spike twi; do
  write_workfile_if_missing "$slug"
  write_status_if_missing "$slug"
  write_mailbox_if_missing "$slug"
done

write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/twi.todo.md" "$(cat <<EOF
# TWILIGHT TODO

Generated: blank

No pending Twilight questions or decisions.
EOF
)"

write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/twi.decisions.md" "$(cat <<EOF
# TWILIGHT DECISIONS

## Active Decisions
- none
EOF
)"

write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/twi.event.stream.history.md" "$(cat <<EOF
# TWILIGHT EVENT STREAM HISTORY

## Current State
- pending_review_needed_content: none
EOF
)"

write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/multi.agent.control.md" "$(cat <<EOF
# MULTI AGENT CONTROL

Blank project-local coordination state for $AGENIC_PROJECT_NAME on $AGENIC_PROJECT_BRANCH.
EOF
)"

write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/twi.review-needed" ""

cat <<EOF
Bootstrapped project-local Agenic Pony state.
- project_root: $AGENIC_PROJECT_ROOT
- branch: $AGENIC_PROJECT_BRANCH
- state_root: $AGENIC_STATE_ROOT
EOF
