#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$script_dir/../pony/scripts/pony-paths.sh"

target_root="${1:-$PWD}"
load_project_paths "$target_root"

while IFS= read -r dir; do
  mkdir -p "$dir"
done < <(project_pony_dirs)

write_file_if_missing() {
  local path="${1:?missing path}"
  local content="${2-}"
  if [[ ! -e "$path" ]]; then
    printf '%s' "$content" >"$path"
  fi
}

copy_file_if_missing() {
  local source_path="${1:?missing source path}"
  local target_path="${2:?missing target path}"
  if [[ ! -e "$target_path" ]]; then
    cp "$source_path" "$target_path"
  fi
}

write_workfile_if_missing() {
  local slug="${1:?missing worker slug}"
  local title
  title="$(worker_label_for_slug "$slug")"
  local workfile="$AGENIC_PROJECT_PONY_WORK_DIR/$(workfile_name_for_slug "$slug")"
  write_file_if_missing "$workfile" "$(cat <<EOF
# ${title} Workfile

Project: $AGENIC_PROJECT_NAME
Branch: $AGENIC_PROJECT_BRANCH

Status: blank
Scope: unassigned
Notes:
- no assigned work yet
EOF
)"
}

write_project_config_if_missing() {
  write_file_if_missing "$AGENIC_PROJECT_PONY_CONFIG_PATH" "$(cat <<EOF
project_name: $AGENIC_PROJECT_NAME
project_root: $AGENIC_PROJECT_ROOT
branch: $AGENIC_PROJECT_BRANCH
launcher_prefix: $AGENIC_PROJECT_NAME Pony
agenic_system_root: $agenic_root
EOF
)"
}

write_shell_launcher_if_missing() {
  local path="${1:?missing launcher path}"
  local personality="${2:?missing personality}"
  write_file_if_missing "$path" "$(cat <<EOF
#!/usr/bin/env bash
set -euo pipefail
cd "$AGENIC_PROJECT_ROOT"
exec "$AGENIC_PROJECT_PONY_SCRIPTS_DIR/start-session.sh" "$personality"
EOF
)"
  chmod +x "$path"
}

write_status_if_missing() {
  local slug="${1:?missing worker slug}"
  local branch_verified="yes"
  if [[ "$AGENIC_PROJECT_BRANCH" == "no-git-branch" ]]; then
    branch_verified="n/a"
  fi
  write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/${slug}.status.md" "$(cat <<EOF
AUDIENCE: EVERYONE
BRANCH: $AGENIC_PROJECT_BRANCH
WORKTREE: $AGENIC_PROJECT_ROOT
BRANCH_VERIFIED: $branch_verified
STATUS: WAITING
PUSH_STATUS: clean_local_branch
FILES_PLANNED: none
FILES_TOUCHED: none
BLOCKERS: none
NEXT_STEP: waiting for a concrete task
QUESTIONS_FOR_TWI: none
DECISION_NEEDED: none
EOF
)"
}

write_mailbox_if_missing() {
  local slug="${1:?missing worker slug}"
  local upper_name
  upper_name="$(printf '%s' "$slug" | tr '[:lower:]' '[:upper:]')"
  write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/${slug}.mailbox.md" "$(cat <<EOF
# ${upper_name} MAILBOX

## Pending Items
- none

EOF
)"
}

write_file_if_missing "$AGENIC_PROJECT_PONY_DIR/README.md" "$(cat <<EOF
# pony

Project-local pony runtime state for $AGENIC_PROJECT_NAME.

This directory is generated by:
$agenic_root/scripts/bootstrap-project.sh
EOF
)"

write_project_config_if_missing

for prompt_template in "$pony_launch_prompts_dir"/*.txt; do
  copy_file_if_missing "$prompt_template" "$AGENIC_PROJECT_PONY_LAUNCH_PROMPTS_DIR/$(basename "$prompt_template")"
done

write_file_if_missing "$AGENIC_PROJECT_PONY_SCRIPTS_DIR/pony.zsh.support.zsh" "$(cat <<EOF
[[ -x ./pony/bin/codex-pony ]] || return 0

twilight()   { export PERSONALITY=TWILIGHT_SPARKLE; }
twi()        { export PERSONALITY=TWILIGHT_SPARKLE; }
rainbow()    { export PERSONALITY=RAINBOW_DASH; }
rd()         { export PERSONALITY=RAINBOW_DASH; }
dash()       { export PERSONALITY=RAINBOW_DASH; }
dashie()     { export PERSONALITY=RAINBOW_DASH; }
pinkie()     { export PERSONALITY=PINKIE_PIE; }
rarity()     { export PERSONALITY=RARITY; }
rares()      { export PERSONALITY=RARITY; }
applejack()  { export PERSONALITY=APPLEJACK; }
aj()         { export PERSONALITY=APPLEJACK; }
shy()        { export PERSONALITY=FLUTTERSHY; }
fluttershy() { export PERSONALITY=FLUTTERSHY; }
flutters()   { export PERSONALITY=FLUTTERSHY; }
spike()      { export PERSONALITY=SPIKE; }
w()          { export WORKING_ON="\$1"; }
clearwork()  { unset WORKING_ON; }
clearpony()  { unset PERSONALITY; }
clearrole()  { unset PERSONALITY WORKING_ON; }
codexpony()  { ./pony/bin/codex-pony "\$@"; }
EOF
)"

write_file_if_missing "$AGENIC_PROJECT_PONY_BIN_DIR/codex-pony" "$(cat <<EOF
#!/usr/bin/env bash
set -euo pipefail
exec "$agenic_root/pony/bin/codex-pony" "\$@"
EOF
)"
chmod +x "$AGENIC_PROJECT_PONY_BIN_DIR/codex-pony"

write_file_if_missing "$AGENIC_PROJECT_PONY_SCRIPTS_DIR/start-session.sh" "$(cat <<EOF
#!/usr/bin/env bash
set -euo pipefail
exec "$agenic_root/pony/scripts/start-session.sh" "\${1:?missing personality}" "$AGENIC_PROJECT_ROOT"
EOF
)"
chmod +x "$AGENIC_PROJECT_PONY_SCRIPTS_DIR/start-session.sh"

write_shell_launcher_if_missing "$AGENIC_PROJECT_PONY_BIN_DIR/pony-team-twi" "TWILIGHT_SPARKLE"
write_shell_launcher_if_missing "$AGENIC_PROJECT_PONY_BIN_DIR/pony-aj" "APPLEJACK"
write_file_if_missing "$AGENIC_PROJECT_PONY_BIN_DIR/pony-team" "$(cat <<EOF
#!/usr/bin/env bash
set -euo pipefail
cd "$AGENIC_PROJECT_ROOT"
printf '%s\n' "Project-local launcher set:"
printf '%s\n' "- ./pony/bin/pony-team-twi"
printf '%s\n' "- ./pony/bin/pony-aj"
printf '%s\n' ""
printf '%s\n' "Warp users can use the generated project-specific launch configurations under:"
printf '%s\n' "./pony/launch.configs"
EOF
)"
chmod +x "$AGENIC_PROJECT_PONY_BIN_DIR/pony-team"

write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/assignment.registry.tsv" "$(cat <<EOF
assignment_id	worker_label	personality	repo	branch	worktree	workfile	promptfile	scope
aj	AJ	APPLEJACK	$AGENIC_PROJECT_NAME	$AGENIC_PROJECT_BRANCH	$AGENIC_PROJECT_ROOT	$AGENIC_PROJECT_PONY_WORK_DIR/aj.md	$AGENIC_PROJECT_PONY_LAUNCH_PROMPTS_DIR/aj.txt	unassigned
pinkie	Pinkie	PINKIE_PIE	$AGENIC_PROJECT_NAME	$AGENIC_PROJECT_BRANCH	$AGENIC_PROJECT_ROOT	$AGENIC_PROJECT_PONY_WORK_DIR/pinkie.md	$AGENIC_PROJECT_PONY_LAUNCH_PROMPTS_DIR/pinkie.txt	unassigned
fs	FS	FLUTTERSHY	$AGENIC_PROJECT_NAME	$AGENIC_PROJECT_BRANCH	$AGENIC_PROJECT_ROOT	$AGENIC_PROJECT_PONY_WORK_DIR/fs.md	$AGENIC_PROJECT_PONY_LAUNCH_PROMPTS_DIR/fs.txt	unassigned
rarity	Rarity	RARITY	$AGENIC_PROJECT_NAME	$AGENIC_PROJECT_BRANCH	$AGENIC_PROJECT_ROOT	$AGENIC_PROJECT_PONY_WORK_DIR/rarity.md	$AGENIC_PROJECT_PONY_LAUNCH_PROMPTS_DIR/rarity.txt	unassigned
rd	RD	RAINBOW_DASH	$AGENIC_PROJECT_NAME	$AGENIC_PROJECT_BRANCH	$AGENIC_PROJECT_ROOT	$AGENIC_PROJECT_PONY_WORK_DIR/rd.md	$AGENIC_PROJECT_PONY_LAUNCH_PROMPTS_DIR/rd.txt	unassigned
spike	Spike	SPIKE	$AGENIC_PROJECT_NAME	$AGENIC_PROJECT_BRANCH	$AGENIC_PROJECT_ROOT	$AGENIC_PROJECT_PONY_WORK_DIR/spike.md	$AGENIC_PROJECT_PONY_LAUNCH_PROMPTS_DIR/spike.txt	unassigned
twi	Twilight	TWILIGHT_SPARKLE	$AGENIC_PROJECT_NAME	$AGENIC_PROJECT_BRANCH	$AGENIC_PROJECT_ROOT	$AGENIC_PROJECT_PONY_WORK_DIR/coordinator-twi.md	$AGENIC_PROJECT_PONY_LAUNCH_PROMPTS_DIR/twi.txt	coordinate the team
EOF
)"

for slug in aj pinkie fs rarity rd spike twi; do
  write_workfile_if_missing "$slug"
  write_status_if_missing "$slug"
  write_mailbox_if_missing "$slug"
done

write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/twi.todo.md" "$(cat <<EOF
# TWILIGHT TODO

Generated: blank

No pending Twilight questions or decisions.
EOF
)"

write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/twi.decisions.md" "$(cat <<EOF
# TWILIGHT DECISIONS

## Active Decisions
- none
EOF
)"

write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/twi.event.stream.history.md" "$(cat <<EOF
# TWILIGHT EVENT STREAM HISTORY

## Current State
- pending_review_needed_content: none
EOF
)"

write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/multi.agent.control.md" "$(cat <<EOF
# MULTI AGENT CONTROL

Blank project-local coordination state for $AGENIC_PROJECT_NAME on $AGENIC_PROJECT_BRANCH.
EOF
)"

write_file_if_missing "$AGENIC_TEAM_COORDINATION_DIR/twi.review-needed" ""

cat <<EOF
Bootstrapped project-local pony state.
- project_root: $AGENIC_PROJECT_ROOT
- branch: $AGENIC_PROJECT_BRANCH
- pony_root: $AGENIC_PROJECT_PONY_DIR
- shell_launchers: $AGENIC_PROJECT_PONY_BIN_DIR/pony-team, $AGENIC_PROJECT_PONY_BIN_DIR/pony-team-twi, $AGENIC_PROJECT_PONY_BIN_DIR/pony-aj
EOF
write_file_if_missing "$AGENIC_PROJECT_PONY_LINUX_SHELL_MARKER" ""
